- hosts: mongo
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: gnupg
        state: present
        update_cache: yes

    - name: Add MongoDB GPG key
      ansible.builtin.apt_key:
        url: https://pgp.mongodb.com/server-7.0.asc
        state: present

    - name: Add MongoDB repo
      ansible.builtin.apt_repository:
        repo: deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
        state: present
        filename: 'mongodb-org-7.0'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Install MongoDB shell client
      ansible.builtin.apt:
        name: mongodb-clients
        state: present

    - name: Configure mongod.conf for replica set
      blockinfile:
        path: /etc/mongod.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          replication:
            replSetName: "rs0"
      notify: Restart MongoDB

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted

- hosts: mongo[0]
  become: yes
  tasks:
    - name: Initiate replica set
      shell: |
        mongo --eval '
          rs.initiate({
            _id: "rs0",
            members: [
              {% for host in groups["mongo"] %}
              { _id: {{ loop.index0 }}, host: "{{ hostvars[host].ansible_host }}:27017" }{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          })
        '
      args:
        executable: /bin/bash
      when: inventory_hostname == groups['mongo'][0]